name: Crawl EmiratesRED and build JSON dataset

on:
  workflow_dispatch:        # manual trigger
  schedule:
    - cron: "0 20 * * *"    # every day at 8 PM UTC (~midnight Dubai)

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # to push updated JSON back to repo
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run scraper
        run: python emiratesred_full_scraper.py

      - name: Commit & push updated JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add emiratesred_products.jsonl
          git commit -m "Update EmiratesRED product dataset [$(date)]" || echo "No changes to commit"
          git push
