name: Crawl EmiratesRED and build JSON dataset

on:
  workflow_dispatch:        # Manual trigger from GitHub UI
  schedule:
    - cron: "0 20 * * *"    # Every day at 8 PM UTC (~midnight Dubai)

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        working-directory: emiratesred-scraper
        run: |
          pip install -r requirements.txt

      - name: Run EmiratesRED scraper
        working-directory: emiratesred-scraper
        run: python emiratesred_full_scraper.py

      - name: Convert JSONL to JSON
        working-directory: emiratesred-scraper
        run: |
          echo "Converting JSONL → JSON array"
          python convert_jsonl_to_json.py

      - name: Commit and push updated JSON files
        working-directory: emiratesred-scraper
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add emiratesred_products.jsonl emiratesred_products.json
          git commit -m "Auto-update EmiratesRED dataset [$(date)]" || echo "No changes to commit"
          git push
